# Generated by Django 4.0.2 on 2022-02-17 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct', models.DateTimeField(auto_now_add=True)),
                ('mt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='名称', max_length=32)),
                ('begin', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('renew_period', models.IntegerField(default=30, verbose_name='续约周期')),
                ('price', models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='价格')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
