# Generated by Django 4.0.2 on 2022-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribemodel',
            name='cycle_begin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subscribemodel',
            name='cycle_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subscribemodel',
            name='renew_price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, null=True, verbose_name='自动续费价格'),
        ),
        migrations.AlterField(
            model_name='subscribemodel',
            name='begin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscribemodel',
            name='end',
            field=models.DateField(),
        ),
    ]
