name: Publish Page
on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend
      - name: install
        run: yarn
        working-directory: frontend
      - name: build
        run: yarn build --outDir=../docs
        working-directory: frontend

      - name: push to specific pages/docs
        run: |
          git config user.email "luliangce@gmail.com"
          git config user.name "Lu.L"
          git checkout --orphan=pages
          git rm --cached -r .
          git add docs
          git commit -m "deploy page"
          git push origin HEAD:pages -f
